Mission04_jf672/Mission04_jf672/Models/CalculatorModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Mission04_jf672.Models
{
    public class CalculatorModel
    {
        [Required]
        [Range(0,100)]
        public int Assign { get; set; }

        [Required]
        [Range(0,100)]
        public int Group { get; set; }

        [Required]
        [Range(0, 100)]
        public int Quiz { get; set; }

        [Required]
        [Range(0, 100)]
        public int Midterm { get; set; }

        [Required]
        [Range(0, 100)]
        public int Final { get; set; }

        [Required]
        [Range(0, 100)]
        public int Intex { get; set; }

    }
}

Mission04_jf672/Mission04_jf672/Controllers/FolderController.cs
using Microsoft.AspNetCore.Mvc;
using Mission04_jf672.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission04_jf672.Controllers
{
    public class FolderController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Calculator()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Calculator(CalculatorModel model)
        {
            return View();
        }
    }

}

Mission04_jf672/Mission04_jf672/Views/Folder/Calculator.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{      
    ViewData["Title"] = "Grade Calculator";
    ViewData["Header"] = "Grade Calculator";   
}

@model CalculatorModel; 

<div class="text-center">
    
    <form method="post" asp-controller="Folder" asp-action="Calculator">
        <label>Assignments:</label>
        <input id="assign" asp-for="Assign"/>
        <br />
        <label>Group Projects:</label>
        <input id="group" asp-for="Group"/>
        <br />
        <label>Quizzes:</label>
        <input id="quiz" asp-for="Quiz"/>
        <br />
        <label>Midterm Exam:</label>
        <input id="midterm" asp-for="Midterm"/>
        <br />
        <label>Final Exam:</label>
        <input id="final" asp-for="Final"/>
        <br />
        <label>INTEX:</label>
        <input id="intex" asp-for="Intex"/>
        <br />
        <input id="btnCalc" type="submit" value="Calculate Grade" />
        <br />
        <p id="score"></p>

        <div asp-validation-summary="All"></div>
    </form>
</div>
<script src="~/js/GradeCalculator.js"></script>

Mission04_jf672/Mission04_jf672/Views/Folder/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Welcome to ME!";
    ViewData["Header"] = "Jeremy Fairbanks";
}



<div class="text-center">
    
    <img src="~/img/LakeTrout.jpg" />
    <p>
        I am getting more and more excited to learn C# as I write these programs and see how much
        easier it is than other languages.
    </p>
    <p>
        Hopefully by the end of the class I will be able to say that I
        can program in C# and impress future employers.
    </p>
    <br />
    <p>
        Careers I am interested in:
    </p>
</div>
<div class="mydiv">
    <ol class="myOl">
        <li>
            Software Developer
        </li>
        <li>
            Data Analyst
        </li>
        <li>
            Cyber-Security Consultant
        </li>
    </ol>
</div>
<br />

Mission04_jf672/Mission04_jf672/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>

<head>

    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />
    <link rel="icon" type="image/png" href="~/img/fishy.png" />
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/default.css" rel="stylesheet" />
    <title>@ViewData["Title"]</title>

</head>

<body>
    <nav>
        <a asp-controller="Folder" asp-action="Index">Home</a>
        <a asp-controller="Folder" asp-action="Calculator">Calculate Grade</a>
    </nav>
    <div class="text-center">
        <h1>@ViewData["Header"]</h1>
    </div>
    <div>
        @RenderBody()
    </div>

    <div class="myFooter">
        <footer class="text-center">jf672 Section 3</footer>
    </div>

    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/lib/jQuery/jquery-3.6.3.min.js"></script>

</body>
    
</html>